# WebApi App
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orleans
  labels:
    run: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  strategy: {}
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - image: orleans-api-image # image name updated by Makefile
        name: api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
--- 

# WebApi Service
apiVersion: v1
kind: Service
metadata:
  namespace: orleans
  labels:
    run: api
  name: api
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 80
  selector:
    run: api
  type: LoadBalancer
---

# Silo App
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: orleans
  labels:
    run: silo
  name: silo
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 8
  selector:
    matchLabels:
      run: silo
  template:
    metadata:
      labels:
        run: silo
    spec:
      containers:
      - image: orleans-silo-image # image name updated by Makefile
        name: silo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11111
        - containerPort: 30000
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
---

# Silo Service
apiVersion: v1
kind: Service
metadata:
  namespace: orleans
  labels:
    run: silo
  name: silo
spec:
  ports:
  - port: 8524
    name: dashboard
    protocol: TCP
    targetPort: 8524
  - port: 8880
    name: health
    protocol: TCP
    targetPort: 8880
  selector:
    run: silo
  type: LoadBalancer
---