version: '3'

services:
  ci-build:
    image: mcr.microsoft.com/dotnet/core/sdk:2.1 AS build
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./OrleansContainer.sln && dotnet publish ./OrleansContainer.sln -c Release -o ./obj/Docker/publish"
